version: 2
updates:

# Main
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - "ChristophWurst"
  - "kesselb"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
  reviewers:
  - "ChristophWurst"
  - "GretaD"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
  - php
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  reviewers:
  - "ChristophWurst"
  - "kesselb"
- package-ecosystem: composer
  directory: "/vendor-bin/mozart/"
  schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
      - 3. to review
      - dependencies
      - php
  allow:
      - dependency-type: direct
  reviewers:
  - "ChristophWurst"
  - "kesselb"
- package-ecosystem: composer
  directory: "/vendor-bin/cs-fixer/"
  schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
      - 3. to review
      - dependencies
      - php
  allow:
      - dependency-type: direct
  reviewers:
  - "ChristophWurst"
  - "kesselb"
- package-ecosystem: composer
  directory: "/vendor-bin/phpunit/"
  schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
      - 3. to review
      - dependencies
      - php
  allow:
      - dependency-type: direct
  reviewers:
  - "ChristophWurst"
  - "kesselb"
